from wtforms import *

class f(Form):
    title    = TextField('title',[validators.Required("The field is required")])
    code     = TextAreaField('code',[validators.Required("The field is required")])
    PL 		 = SelectField(choices=[('cpp', 'c++')
    	, ('python', 'Python')
    	, ('php', 'PHP')
    	, ('d', 'D')
    	, ('delphi', 'Delphi')
    	, ('pascal', 'Pascal')
    	, ('go', 'Go')
    	, ('csharp', 'C#')
    	, ('fsharp', 'F#')
    	, ('lisp', 'Lisp')
    	, ('erlang', 'Erlang')
    	, ('haskell', 'Haskell')
    	, ('scheme', 'Scheme')
    	, ('java', 'Java')
    	, ('scala', 'Scala')
    	, ('matlab', 'Matlab')
    	, ('ruby', 'Ruby')
    	, ('c', 'C')
    	, ('html', 'HTML')
    	, ('js', 'Javascript')
    	, ('css', 'CSS')
        , ('lua', 'Lua')
        , ('perl', 'Perl')
        , ('python3', 'Python 3')
        , ('objective-c', 'Objective-c')
        , ('prolog', 'Prolog')
        , ('rust', 'Rust')
        , ('applescript', 'Applescript')
        , ('text', 'Text')
        , ('mysql', 'Mysql')
        , ('postgresql', 'Postgresql')
        , ('sqlite3', 'Sqlite3')
        , ('jinja', 'Jinja template')
        , ('django', 'Django')
        , ('jsp', 'Jsp')
        , ('smarty', 'Smarty template')
        , ('nginx', 'Nginx')
        , ('yaml', 'Yaml')
        , ('dart', 'Dart')
        , ('json', 'Json')
        , ('xml', 'XML')
    	])
    